# 9 Numpy

Generate matrices A, with random Gaussian entries, B, a Toeplitz matrix, where A ∈ R
n×m and B ∈ Rm×m, for n = 200, m = 500.

In [2]:
import numpy as np
from scipy.linalg import toeplitz
import time

A = np.random.normal(0, 1.0, (200, 500))
c = []
for a in range(1, 501):
    c.append(a)
    
B = toeplitz(c, c)
print("A=\n",A)
print("\nB=\n",B)

A=
 [[-0.10489967 -1.73525189 -0.11485847 ... -0.52626661  0.09255169
   0.57463982]
 [-0.99255149  0.77432803  1.70324006 ...  1.08752048 -1.15558414
  -0.09349061]
 [-0.03931532 -1.3999558  -0.43064251 ... -1.1388219   0.43987179
  -0.51428279]
 ...
 [ 0.77383593  0.1275814   1.60896911 ... -1.59374704  0.70773484
  -1.10652563]
 [-3.46924209 -0.75987212  0.76815626 ...  2.22106423  0.0986837
  -0.3771497 ]
 [-1.17502181 -0.74274707 -0.7717577  ...  2.08247521  1.51764688
   0.49323232]]

B=
 [[  1   2   3 ... 498 499 500]
 [  2   1   2 ... 497 498 499]
 [  3   2   1 ... 496 497 498]
 ...
 [498 497 496 ...   1   2   3]
 [499 498 497 ...   2   1   2]
 [500 499 498 ...   3   2   1]]


### Exercise 9.1: Matrix operations


Calculate A + A, A(A^T), (A^T)A and AB. Write a function that computes A(B − λI) for any λ.

In [4]:
#A+A
print("A+A=\n", A+A)
    
#A(A^T)
print("\nA(A^T)=\n", np.dot(A, A.T))
    
#(A^T)A
print("\n(A^T)A=\n", np.dot(A.T, A))
    
#AB
print("\nAB=\n", np.dot(A, B))
    
def lambda_function(A, B, lamda):
    print("\nThe result of A(B − λI):")
    C = B - (lamda * (np.eye(500)))
    print(np.dot(A, C))
    
lambda_function(A, B, 2.0);

A+A=
 [[-0.20979933 -3.47050379 -0.22971694 ... -1.05253323  0.18510338
   1.14927964]
 [-1.98510299  1.54865605  3.40648011 ...  2.17504096 -2.31116828
  -0.18698122]
 [-0.07863064 -2.79991159 -0.86128501 ... -2.27764379  0.87974358
  -1.02856558]
 ...
 [ 1.54767187  0.25516279  3.21793823 ... -3.18749409  1.41546968
  -2.21305127]
 [-6.93848418 -1.51974425  1.53631252 ...  4.44212847  0.1973674
  -0.7542994 ]
 [-2.35004361 -1.48549415 -1.5435154  ...  4.16495041  3.03529376
   0.98646465]]

A(A^T)=
 [[469.60735754  -4.99592707   8.33077266 ... -39.56295437  47.6048915
    1.32648614]
 [ -4.99592707 525.05510999  11.43904042 ...  -4.73183406  13.53597161
   -0.84406771]
 [  8.33077266  11.43904042 521.58353352 ...  13.83278923  -5.97265708
   -2.43986023]
 ...
 [-39.56295437  -4.73183406  13.83278923 ... 506.6796173   -5.29443107
   11.45679532]
 [ 47.6048915   13.53597161  -5.97265708 ...  -5.29443107 530.05949917
   11.70622197]
 [  1.32648614  -0.84406771  -2.43986023 ...  11.45679

### Exercise 9.2: Solving a linear system

Generate a vector b with m entries and solve Bx = b.

In [5]:
b = np.ones((500, 1))
#Bx = b
x = np.linalg.solve(B, b)

#Print the solution
print(x)

#Check the solution
np.allclose(np.dot(B, x), b)

[[ 1.99600798e-03]
 [ 2.91592944e-16]
 [ 4.87523085e-18]
 [-5.64861974e-16]
 [ 4.44089210e-16]
 [ 1.20772764e-16]
 [-6.73446661e-16]
 [ 5.52673897e-16]
 [-9.63966099e-17]
 [ 3.11128369e-16]
 [-5.33172974e-16]
 [ 1.97668451e-16]
 [-2.00106066e-16]
 [ 2.24482220e-16]
 [ 8.42085328e-17]
 [ 6.82532319e-17]
 [-4.15945832e-16]
 [ 3.84256831e-16]
 [ 1.56228988e-16]
 [-1.36728065e-16]
 [-3.94007293e-16]
 [ 3.45254985e-16]
 [-2.24482220e-16]
 [-1.92793220e-16]
 [ 7.96657041e-16]
 [-9.85683037e-16]
 [ 4.25696293e-16]
 [ 3.23316446e-16]
 [-1.45148918e-16]
 [-5.89238128e-16]
 [ 1.34068848e-15]
 [-1.46633648e-15]
 [ 8.67347888e-16]
 [-4.03757755e-16]
 [ 3.48800607e-16]
 [-1.31631233e-16]
 [ 5.49571477e-17]
 [-1.50245751e-16]
 [ 5.08796819e-16]
 [-1.89025996e-16]
 [-1.72516692e-15]
 [ 1.80073299e-15]
 [-1.46256925e-16]
 [-9.97206310e-18]
 [ 3.78938398e-17]
 [-5.12342442e-16]
 [ 3.48800607e-16]
 [ 3.92234482e-17]
 [-5.99210191e-16]
 [ 6.55275346e-16]
 [-1.06147072e-16]
 [-5.41815428e-16]
 [ 7.2109096

True

### Exercise 9.3: Norms

Compute the Frobenius norm of A: kAkF and the infinity norm of B: kBk∞. Also find the largest and
smallest singular values of B.

In [10]:
#Frobenius norm
A_form = np.linalg.norm(A,'fro')
print("the Frobenius norm:", A_form)
    
#the infinity norm
B_form = np.linalg.norm(B, np.inf)
print("the infinity norm:", B_form)
        
#the largest and smallest singular values of B
largest_singular = np.linalg.norm(B, 2)
smallest_singular = np.linalg.norm(B, -2)
print("largest singular:", largest_singular)
print("smallest singular:", smallest_singular)

the Frobenius norm: 316.23032411164013
the infinity norm: 125250.0
largest singular: 87334.52045641867
smallest singular: 0.5000049348346838


### Exercise 9.4: Power iteration


Generate a matrix Z, n × n, with Gaussian entries, and use the power iteration to find the largest
eigenvalue and corresponding eigenvector of Z. How many iterations are needed till convergence?
Optional: use the time.clock() method to compare computation time when varying n.

In [11]:
def power_iteration(A, B, n, m):
    #Generate a matrix Z, n × n, with Gaussian entries
    Z = np.random.standard_normal((n, n))
    #use the power iteration to find the largest eigenvalue and corresponding eigenvector of Z
    num = 0
    u_k = np.ones(n)
    v_k_norm = 0
    v_k = np.zeros(n)
    
    #time.clock() is deprecated so I used time.process_time()
    start = time.process_time()
    while(True):
        # calculate the matrix-by-vector product Ab
        v_k = np.dot(Z, u_k)
        
        # calculate the norm
        v_k_norm_temp = v_k_norm
        v_k_norm = np.linalg.norm(v_k)
        
        # re normalize the vector
        u_k = v_k/v_k_norm
        num += 1
        if(abs(v_k_norm_temp-v_k_norm) <0.0005):
            break;
    end = time.process_time()
    
    print("The largest eigenvalue:", v_k_norm)
    print("The corresponding eigenvector:", u_k)
    #How many iterations are needed till convergence?
    print("The number of iterations:", num)
    #Optional: use the time.clock() method to compare computation time when varying n.
    print("Computation time when varying n:", end-start)
    
power_iteration(A, B, 200, 500)

The largest eigenvalue: 15.87590593136984
The corresponding eigenvector: [ 0.0393817  -0.12184421 -0.13579854  0.06768677  0.05382097  0.04893854
  0.20769186 -0.00832565 -0.02012483 -0.03059356  0.01834157 -0.04128827
 -0.09383546 -0.02026506 -0.03954518  0.01100637  0.01031251 -0.00961817
  0.03456972  0.06429967  0.01943208 -0.02440942 -0.0675609   0.03190266
 -0.00471568 -0.07502072  0.02685448  0.07282506 -0.01493588  0.00087409
  0.08267279  0.08759326 -0.13635126  0.02184434  0.14801441  0.03920399
 -0.04123719  0.01254977 -0.05617273  0.10414519  0.05880949  0.01798165
  0.09322386 -0.09917434 -0.09976884 -0.03420731  0.05696201 -0.05252653
 -0.056878   -0.12241143 -0.10797768 -0.03503394 -0.03036036  0.03070213
  0.16001585  0.02874313  0.0246692  -0.06706422 -0.127453    0.09353317
 -0.07985103  0.01448349 -0.03691941 -0.02744172  0.04494404  0.05608474
 -0.07327986  0.02246113  0.12152917 -0.01144506  0.11399016  0.06662072
  0.00883656  0.13966901 -0.02275103 -0.07094055  0

### Exercise 9.6: Nearest neighbor


Write a function that takes a value z and an array A and finds the element in A that is closest to z. The
function should return the closest value, not index.
Hint: Use the built-in functionality of Numpy rather than writing code to find this value manually. In
particular, use brackets and argmin.

In [12]:
def closest(A, z):
    
    B, C = A[A>z], A[A<=z]
    ceil, floor = 0, 0
    
    if(len(B)):
        ceil = np.argmin(B)
    else:
        return C[np.argmax(C)]
    
    if(len(C)):
        floor = np.argmax(C)
    else:
        return B[ceil]

    if(abs(B[ceil]-z) < abs(C[floor]-z)):
        return B[ceil]
    else:
        return C[floor]
    

z = 4
closest_value = closest(A, z)
print("the closest value:", closest_value)

the closest value: 4.0448572574459005
